Repository zigpy/zigpy, pull requests merged in 2020-10, with the labels that each got.

#515 Fix attributes being lost when an existing device is re-added
  tests/test_appdb.py
  zigpy/appdb.py
Labels: bug, hacktoberfest, hacktoberfest-accepted

#528 Refactor persisting listener to use aiosqlite
  setup.py
  tests/test_appdb.py
  zigpy/appdb.py
  zigpy/application.py
Labels: breaking, bug

#529 Cleanup device on restart
  tests/test_appdb.py
  zigpy/appdb.py
Labels: bug
